name: craftalberta
favicon: null
layout_spectrum: 0.16665889346040785
typography_spectrum: 0.78699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e1e21'
    - '#ffffff'
    - '#fccc0a'
    - '#c77017'
    - '#e7c0b8'
  brandStrength: 0.6875
  lightness: 0.8498402987606823
  saturation: 0.3779049846343696
  rhythmicContrast: 0.2232240776065737
purpose: []
